version: '3'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MARIADB_DATABASE: fullcycle
      MARIADB_USER: fullcycle
      MARIADB_PASSWORD: fullcycle
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--user=fullcycle", "--password=fullcycle"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  admin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=fullcycle
      - PMA_PASSWORD=fullcycle
    depends_on:
      db:
        condition: service_healthy

  app:
    image: node
    restart: always
    user: node
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app
    command: bash -c "npm install && npm start"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  proxy:
    image: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      app:
        condition: service_healthy
